### ISSUE TITLE
Events problem

### ISSUE THREAD

**Issue by Scouterdev** [isaackogan/TikTokWidgets#4]
Connected to roomId, but dont fetch events for TikTok cliend..

**Comment by isaackogan** [comment]
Known. Won't be fixed for a few days. There is a temp fix in the issues tab in https://GitHub.com/zerodytrash/tiktok-live-Connector

Isaac

**Comment by carpehh** [comment]
Looking forward to! Thx

**Comment by isaackogan** [comment]
Update via npm
